"""Conservative cleanup of Director items removed from Home Assistant's registries."""

from __future__ import annotations

from collections.abc import Iterable
import logging
from typing import Any

from .const import DOMAIN


_LOGGER = logging.getLogger(__name__)


def _director_id(unique_id: str, host: str) -> int | None:
    """Recognize only IDs generated by this integration for this Director."""
    prefix = f"{host}_"
    if not unique_id.startswith(prefix):
        return None
    suffix = unique_id[len(prefix):]
    if suffix.endswith("_hold_mode"):
        suffix = suffix[:-len("_hold_mode")]
    if not suffix.isascii() or not suffix.isdecimal():
        return None
    device_id = int(suffix)
    return device_id if device_id > 0 else None


def stale_registry_ids(
    entity_entries: Iterable[Any],
    device_entries: Iterable[Any],
    *,
    config_entry_id: str,
    host: str,
    first_inventory_ids: set[int],
    second_inventory_ids: set[int],
) -> tuple[list[str], list[str]]:
    """Plan removal only for owned IDs missing from two complete REST reads."""
    if not first_inventory_ids or not second_inventory_ids:
        return [], []

    def absent(unique_id: str) -> bool:
        device_id = _director_id(unique_id, host)
        return (
            device_id is not None
            and device_id not in first_inventory_ids
            and device_id not in second_inventory_ids
        )

    stale_entities = [
        entity.entity_id
        for entity in entity_entries
        if entity.config_entry_id == config_entry_id
        and entity.platform == DOMAIN
        and isinstance(entity.unique_id, str)
        and absent(entity.unique_id)
    ]
    stale_devices = [
        device.id
        for device in device_entries
        if device.config_entry_id == config_entry_id
        and len(device.identifiers) == 1
        and (
            identifier := next(iter(device.identifiers))
        )[0] == DOMAIN
        and isinstance(identifier[1], str)
        and absent(identifier[1])
    ]
    return stale_entities, stale_devices


def remove_stale_registry_entries(
    hass: Any,
    *,
    config_entry_id: str,
    host: str,
    first_inventory_ids: set[int],
    second_inventory_ids: set[int],
) -> None:
    """Remove confirmed stale entries only after successful platform setup."""
    from homeassistant.helpers import device_registry as dr, entity_registry as er

    entities = er.async_get(hass)
    devices = dr.async_get(hass)
    stale_entities, stale_devices = stale_registry_ids(
        er.async_entries_for_config_entry(entities, config_entry_id),
        dr.async_entries_for_config_entry(devices, config_entry_id),
        config_entry_id=config_entry_id,
        host=host,
        first_inventory_ids=first_inventory_ids,
        second_inventory_ids=second_inventory_ids,
    )
    for entity_id in stale_entities:
        entities.async_remove(entity_id)
    for device_id in stale_devices:
        if devices.async_get(device_id) is not None:
            devices.async_remove_device(device_id)
    if stale_entities or stale_devices:
        _LOGGER.info(
            "Removed %d stale Control4 entities and %d devices from Home Assistant registries",
            len(stale_entities), len(stale_devices),
        )
